import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Menu, X, ExternalLink, Wrench, Zap, Gauge, Battery, Disc3, Car, Settings, Fan, BookOpen, Image as ImageIcon } from 'lucide-react';
import './style.css';

const manualPath = '/manuals/jensen_cv8_owners_manual.pdf';

const sections = [
  { id:'dashboard', title:'Dashboard & Controls', icon:Gauge, pages:[4], tags:['dashboard','instruments','controls','switches','gauges','warning lights'], plain:'The C-V8 dashboard groups the instruments, warning lights, heater controls, lighting switches, ignition, gear selector and auxiliary controls around the driver.', references:'Instruction Book, page 4, Fig. 1: Instruments and Controls list items 1–29.', checklist:['Identify the component by number on the dashboard diagram before removing anything.','Confirm whether the issue is with the switch, warning lamp, gauge, wiring, or sender.','For warning lights, check the relevant bulb and holder before assuming a sender or wiring fault.','Avoid modifying the dashboard layout if originality is important.'] },
  { id:'specifications', title:'Specifications & Capacities', icon:Settings, pages:[5,6], tags:['specifications','capacity','timing','plug gap','compression','weight','dimensions','oil'], plain:'The quick-reference pages cover the core service data: engine bore and stroke, compression ratio, firing order, capacities, gear ratios, tyre size and pressure, alignment figures, ignition timing, plug gap and sump capacity note.', references:'Instruction Book, pages 5–6: General Dimensions and Data for Quick Reference.', keyFacts:['Firing order: 1-8-4-3-6-5-7-2.','Sparking plug point gap: .035 in.','Ignition timing: 10° before T.D.C. at 500 r.p.m.','Tyres: Dunlop 670 x 15 road speed.','Tyre pressure: 24 p.s.i. all round, rising once warm.','Sump capacity: 7 pints Imperial / 8 pints U.S. / 3.6 litres. Do not fill above the high-level mark.'] },
  { id:'motor', title:'Motor, Starting & Running', icon:Car, pages:[6,7,8,9], tags:['engine','starting','running in','gearbox','transmission','overdrive','towing','push starting'], plain:'The running-in guidance is conservative and period-correct: keep sustained high speed down, avoid hard acceleration and watch oil pressure and temperature.', references:'Instruction Book, pages 6–9: Starting Up and General Running Hints, Starting Car Engine, Gearbox Operation, Towing, Push Starting, Optional Manual Transmission and Overdrive.', checklist:['For an automatic car, put the selector in Neutral before starting.','Apply the handbrake before starting; the automatic carburetter control can cause a fast idle when cold.','Depress the accelerator slowly to one-third travel before starting.','When the engine fires, release the key immediately.','If it will not start after a few attempts, press the accelerator fully to clear excess fuel, then operate the starter briefly.','During running-in, avoid prolonged high-speed cruising and watch temperature and oil pressure closely.'] },
  { id:'lubrication', title:'Lubrication & Maintenance', icon:Wrench, pages:[10,11], tags:['lubrication','maintenance','service','grease','oil','miles'], plain:'The manual gives a mileage-based lubrication plan, including first 1,000-mile service and recurring checks at 1,000, 2,000, 4,000 and 8,000 miles.', references:'Instruction Book, pages 10–11: Lubrication and Maintenance schedule and Fig. 3 lubrication chart.', checklist:['At first 1,000 miles: drain/refill axle, check controls, fluid levels, belt, electrical system, tyre pressures, lights and brakes.','Every 1,000 miles: grease king pins, propeller shaft, steering idler and listed points.','Every 2,000 miles: check brake fluid level in the master cylinder.','Every 4,000 miles: grease steering rack, check steering damper, service transmission items and check rear axle oil.','Every 8,000 miles: clean/check air cleaner, distributor points, crankcase ventilation, carburetter choke piston and plugs.'] },
  { id:'electrical', title:'Electrical Equipment', icon:Zap, pages:[12,13], tags:['electrical','Lucas','lamps','headlamps','screenwiper','screencleaner','map light','gear quadrant'], plain:'Most electrical equipment is Lucas, except the ignition, charging and starter systems, which the manual says are Autolite.', references:'Instruction Book, pages 12–13: Electrical Equipment.', keyFacts:['Headlamp flasher is operated by pulling the trafficator control lever backwards.','The screenwiper is a two-speed heavy-duty type, with the motor housed on the scuttle.','Map light bulb access is by removing the central instrument panel.','Gear quadrant light access is from the left-hand side of the panel.'] },
  { id:'battery-charging', title:'Battery & Charging System', icon:Battery, pages:[12], tags:['battery','charging','earth','Autolite','positive earth','battery clamp'], plain:'The manual specifies a 12-volt Lucas battery and notes that the vehicle is positive earth.', references:'Instruction Book, page 12: Battery, Positive Earth.', checklist:['Confirm polarity before connecting accessories: the car is positive earth in the owner’s manual.','Keep the battery firmly secured at all times.','Check electrolyte level about every four weeks.','Top up with distilled water as required, unless the battery type has different modern instructions.','Keep terminals clean and tight.'] },
  { id:'fuses', title:'Fuses', icon:Fan, pages:[12], tags:['fuse','fuses','fuse box','35 amp','electrical fault'], plain:'Both main and auxiliary fuses are 35 amp, and the fuse box is forward and below the right-hand side of the fascia panel.', references:'Instruction Book, page 12: Fuses.', checklist:['Locate the fuse box forward and below the right-hand side of the fascia.','Inspect the 35 amp main and auxiliary fuses.','If a fuse repeatedly blows, do not increase the fuse rating — find the short or overloaded circuit.','Use the original rating for period-correct and safe restoration.'] },
  { id:'brakes', title:'Brakes & Brake Servo', icon:Disc3, pages:[13], tags:['brakes','servo','Dunlop','brake fluid','handbrake','vacuum'], plain:'The C-V8 uses Dunlop hydraulic disc brakes on all wheels with vacuum servo assistance. The handbrake is separate from the hydraulic system.', references:'Instruction Book, page 13: Brakes and Brake Servo.', checklist:['Check the brake fluid level about every 2,000 miles and top up if needed.','Use Dunlop Disc Brake Fluid or a compatible fluid specified by a brake specialist.','Lubricate the brake servo every 12,000 miles as instructed.','Never drill the main frame tubes. They are used as vacuum reservoirs.'] },
  { id:'fuel-carburetter', title:'Fuel System & Carburetter', icon:Gauge, pages:[14,15,16], tags:['fuel','carburetter','Carter','idle','fast idle','choke','fuel tank','filters'], plain:'The fuel section covers the tank, lines, filters, mechanical pump and Carter carburetter, including idle and fast-idle adjustment procedures.', references:'Instruction Book, pages 14–16, Figs. 4–7: Fuel System, Idle Speed Adjustment, Fast Idle Speed Adjustment and Throttle Linkage.', checklist:['Warm the engine thoroughly before making idle adjustments.','Make sure the choke valve is fully open and the fast-idle adjusting screw is clear of the cam.','Set idle speed using the idle speed screw to approximately 500 r.p.m.','Adjust mixture screws carefully for highest r.p.m., then re-check idle speed.','For fast idle, set the fast-idle screw and check the specified cam/index relationship shown in Fig. 6.'] },
  { id:'tyres-wheels', title:'Tyres, Wheels & Alignment', icon:Disc3, pages:[17,18,19], tags:['tyres','tires','wheels','alignment','bearings','front suspension','castor','camber','toe-in'], plain:'The manual specifies Dunlop 670 x 15 RS tyres at 24 psi all round, with pressure checks when cold, plus alignment and bearing adjustment guidance.', references:'Instruction Book, pages 17–19: Care of Tyres, Tyre and Wheel Balance, Factors Affecting Tyre Life, Spare Wheel, Front Suspension, Alignment of Front Wheels and Adjusting Front Wheel Bearings.', keyFacts:['Standard tyre specification: Dunlop 670 x 15 RS.','Correct pressure: 24 p.s.i. all round.','For town use only, rear pressures may be dropped to 22 p.s.i.','For sustained high speed above 90 m.p.h., increase pressure to 30 p.s.i.','Toe-in is measured at wheel height and should be 1/8 inch.'] },
  { id:'cooling-heating', title:'Cooling, Electric Fans & Heater', icon:Fan, pages:[20], tags:['cooling','fan','radiator','heater','anti-freeze','topping up','temperature','pressure cap'], plain:'The cooling section covers automatic electric radiator fans, heater/ventilation controls, coolant circulation and topping up.', references:'Instruction Book, page 20: Electric Cooling Fans, Heating and Ventilation, Cooling System, Topping Up.', checklist:['Do not remove the header tank filler cap when the engine is hot.','Check coolant level weekly, when cold.','Top up to approximately 1 inch below the top of the header tank.','Confirm electric radiator fans operate automatically when coolant temperature rises above normal.'] },
  { id:'rear-axle-drive-belt', title:'Rear Axle & Drive Belt', icon:Settings, pages:[20], tags:['rear axle','Power-Lok','limited slip','drive belt','alternator','water pump'], plain:'The rear axle uses a Power-Lok limited-slip differential. The manual advises against dismantling the axle without the correct tools.', references:'Instruction Book, page 20: Rear Axle and Drive Belt Adjustment.', checklist:['Do not dismantle the rear axle unless the correct Churchill tool is available.','Refer specialist axle work to an experienced workshop familiar with Power-Lok units.','Check the alternator/water pump belt for sufficient tightness to prevent slip.','Adjust by slackening bolts and raising or lowering the alternator in the guide slot.'] }
];

const diagrams = [
  ['Instruments and Controls',4,'Dashboard layout and numbered control list.'],
  ['Lubrication Chart',11,'Underside lubrication and maintenance service points.'],
  ['Carter Carburetter Views',14,'Carburetter component identification diagrams.'],
  ['Fast Idle Adjustment',16,'Fast idle screw, choke valve, cam and connector rod.'],
  ['Accelerator Pedal Adjustment',17,'Pedal rod length adjustment diagram.'],
  ['Front Wheel Bearing Section',19,'Cross-section of front hub and bearing assembly.']
];

function App(){
  const [query,setQuery]=useState('');
  const [active,setActive]=useState('dashboard');
  const [menu,setMenu]=useState(false);
  const filtered=useMemo(()=>{const q=query.toLowerCase().trim(); if(!q) return sections; return sections.filter(s=>[s.title,s.plain,s.references,...s.tags,...(s.keyFacts||[]),...(s.checklist||[])].join(' ').toLowerCase().includes(q));},[query]);
  const current=sections.find(s=>s.id===active)||filtered[0]||sections[0]; const Icon=current.icon;
  const openManual=(p)=> window.open(`${manualPath}#page=${p}`,'_blank');
  return <div className="app">
    <header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><div className="badge">J</div><div><div className="kicker">Jensen Model C-V8</div><h1>Searchable Manual Archive</h1></div><a className="manual" href={manualPath} target="_blank"><BookOpen size={17}/> Open PDF</a></header>
    <div className="layout">
      <aside className={menu?'open':''}><button className="close" onClick={()=>setMenu(false)}><X/></button><label><Search size={16}/> Instant search</label><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try fuses, brakes, idle…" />{filtered.map(s=>{const I=s.icon; return <button key={s.id} className={current.id===s.id?'selected':''} onClick={()=>{setActive(s.id);setMenu(false)}}><I size={18}/><span>{s.title}</span><em>p{s.pages.join(',')}</em></button>})}</aside>
      <main>
        <section className="card hero"><div className="pill"><Icon size={16}/> Pages {current.pages.join(', ')}</div><h2>{current.title}</h2><p>{current.plain}</p><div className="actions">{current.pages.map(p=><button key={p} onClick={()=>openManual(p)}>View scan p{p} <ExternalLink size={14}/></button>)}</div><div className="source"><b>Source reference</b><br/>{current.references}</div>{current.keyFacts&&<div className="facts">{current.keyFacts.map(f=><div key={f}>{f}</div>)}</div>}{current.checklist&&<div className="check"><h3>Repair / diagnostic checklist</h3><ol>{current.checklist.map((c,i)=><li key={c}><span>{i+1}</span>{c}</li>)}</ol></div>}</section>
        <section className="card"><h2><ImageIcon/> Diagrams & Schematics Gallery</h2><div className="gallery">{diagrams.map(([t,p,c])=><button key={t} onClick={()=>openManual(p)}><div className="thumb"><ImageIcon/></div><b>{t}</b><p>{c}</p><small>View page {p} ↗</small></button>)}</div></section>
      </main>
    </div>
  </div>
}

createRoot(document.getElementById('root')).render(<App/>);
